name: Helidon Project compile
on: [push]

jobs:
  HelidonMavenPackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '22'
      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true --file pom.xml